services:
  - type: web
    name: student-management
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py import_sql
      python manage.py collectstatic --noinput
    startCommand: gunicorn student_management.wsgi:application --workers 2 --worker-class sync --timeout 120 --access-logfile - --log-level info
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: DATABASE_URL
        value: postgresql://student_by62_user:sAptb2lyFAlL0RNIcPdDCUbXEgY74fQa@dpg-d8r07jegvqtc73ebmm9g-a.oregon-postgres.render.com/student_by62
      - key: PGHOST
        value: dpg-d8r07jegvqtc73ebmm9g-a.oregon-postgres.render.com
      - key: PGPORT
        value: '5432'
      - key: PGDATABASE
        value: student_by62
      - key: PGUSER
        value: student_by62_user
      - key: PGPASSWORD
        value: sAptb2lyFAlL0RNIcPdDCUbXEgY74fQa
